[package]
name = "BaseBuster"
version = "1.85.0"
edition = "2021"

[profile.release]
debug = true

[features]
verification = []

[dependencies]
# Core
anyhow = "1.0.79"
eyre = "0.6.12"
log = "0.4.21"
env_logger = "0.11.3"
lazy_static = "1.4.0"

# Async
tokio = { version = "1.37.0", features = ["full"] }
futures = { version = "0.3.30", features = ["executor"] }

# Networking & HTTP
reqwest = { version = "0.12.3", features = ["json", "gzip", "blocking", "stream"] }
hyper = { version = "1.3.0", features = ["client"] }
hyper-tls = { version = "0.6.0", features = ["alpn"] }
hyper-util = { version = "0.1.11", features = ["client", "client-legacy", "http1", "http2"] }
http-body-util = "0.1.1"
bytes = "1.6.0"

# Data formats & serialization
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"

# Cryptography & math
sha2 = "0.10.8"
rustc-hash = "1.1.0"
uniswap_v3_math = "0.5.2"

# Time
chrono = "0.4.38"

# Ethereum / Smart contract
alloy = { version = "0.6.4", features = ["full"] }
alloy-consensus = "0.4.2"

# REVM stack (uses c-kzg 1.0.3 transitively)
revm = { version = "18.0.0", features = ["alloydb"] }
revm-inspectors = "0.12.0"
revm-precompile = "15.0.0"
revm-database = { version = "3.0.0" }

# # Reth
reth = { git = "https://github.com/paradigmxyz/reth", rev = "7b435e0" }
# reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", rev = "7b435e0" }
# reth-chainspec = { git = "https://github.com/paradigmxyz/reth", package = "reth-chainspec", rev = "7b435e0" }
# reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-ethereum", rev = "7b435e0" }

# reth = { git = "https://github.com/paradigmxyz/reth", tag = "v0.1.0-alpha.11" }
# reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", tag = "v0.1.0-alpha.11" }
# reth-chainspec = { git = "https://github.com/paradigmxyz/reth", package = "reth-chainspec", tag = "v0.1.0-alpha.11" }
# reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-ethereum", tag = "v0.1.0-alpha.11" }


# Utilities
rayon = "1.10.0"
petgraph = "0.6.5"
dashmap = "5.5.3"
zerocopy = "0.8.6"
foldhash = "0.1.3"
dotenv = "0.15.0"

# Local
node-db = { path = "./NodeDB" }
pool-sync = "3.0.0"

# Optional SQL support
essential-node-db-sql = "0.5.0"
