[package]
name = "BaseBuster"
version = "1.86.0"

[profile.release]
debug = true

[features]
verification = []
serde = ["dep:serde"]
alloy = ["dep:alloy"]
revm = ["dep:revm"]
reqwest = ["dep:reqwest"]
reth = ["dep:reth"]
pool-sync = ["dep:pool-sync"]
uniswap_v3_math = ["dep:uniswap_v3_math"]
petgraph = ["dep:petgraph"]
alloy-primitives = ["dep:alloy-primitives"]

[dependencies]
anyhow = "1.0.79"
eyre = "0.6.12"
log = "0.4.21"
env_logger = "0.11.3"
lazy_static = "1.4.0"
block-db = "0.2.0"
blockstate = "0.1.0"
winit = "0.30.9"
tokio = { version = "1.44.2", features = ["full"] }
futures = { version = "0.3.31", features = ["executor"] }
reqwest = { version = "0.12.3", optional = true, features = ["json", "gzip", "blocking", "stream"] }
hyper = { version = "1.3.0", features = ["client"] }
hyper-tls = { version = "0.6.0", features = ["alpn"] }
hyper-util = { version = "0.1.11", features = ["client", "client-legacy", "http1", "http2"] }
http-body-util = "0.1.1"
bytes = "1.6.0"
serde = { version = "1.0.197", optional = true, features = ["derive"] }
serde_json = "1.0.114"
sha2 = "0.10.8"
rustc-hash = "2.1.1"
uniswap_v3_math = { version = "0.6.0", optional = true}
uniswap-v3-sdk = "4.3.0"
chrono = "0.4.38"
alloy = { version = "0.14.0", optional = true, features = ["full"] }
alloy-consensus = "0.14.0"
alloy-eips = "0.14.0"
alloy-primitives = { version = "1.0.0", optional = true}
alloy-network = "0.14.0"
enr = "0.13.0"
zerocopy = "0.8.25-alpha.3"
revm = { version = "22.0.1", optional = true, features = ["alloydb"] }
revm-inspectors = "0.19.1"
revm-database = "3.0.0"
reth = { git = "https://github.com/paradigmxyz/reth", optional = true, rev = "6f8e725"}
reth-db = { git = "https://github.com/paradigmxyz/reth", package = "reth-db", rev = "6f8e725"}
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", package = "reth-chainspec", rev = "6f8e725"}
reth-node-ethereum = { git = "https://github.com/paradigmxyz/reth", package = "reth-node-ethereum", rev = "6f8e725"}
reth-provider = { git = "https://github.com/paradigmxyz/reth"}
reth-primitives = { git = "https://github.com/paradigmxyz/reth"}
rayon = "1.10.0"
petgraph = { version = "0.8.1", optional = true}
dashmap = "6.1.0"
foldhash = "0.1.3"
dotenv = "0.15.0"
pool-sync = { git = "https://github.com/Zacholme7/PoolSync", optional = true }
essential-node-db-sql = "0.5.0"


